name: build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call API and crunch
        run:  ./.github/scripts/wololo 50 > random-map.json
        shell: bash

      - name: Commit file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'
          git add random-map.json
          git commit -m "chore(data): $(date -u -I)"
          git push

      - name: Upload raw data as artifact
        uses: actions/upload-artifact@v2
        with:
          name: raw-data
          path: ./github/.scripts/raw.txt
          retention-days: 1
