name: build
on:
  workflow_dispatch:
#  schedule:
#    - cron: "0 2 * * *"
jobs:
  update-histogram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call API and generate histogram
        run:  ./.github/scripts/wololo 100 > random-map.json
        shell: bash

      - name: Commit file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'
          git add random-map.json
          git commit -m "chore(data): $(date -u -I)"
          git push
