name: test-actions
on: workflow_dispatch
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Call API and generate histogram
        run:  ./.github/scripts/script > hist.txt
        shell: bash

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'
          git commit -am "chore(data): $(date -u -I)"
          git push
